### ISSUE TITLE
"Xrm Context is not available" when used in Web Resource

### ISSUE THREAD

**Issue by geerzo** [AleksandrRogov/DynamicsWebApi#15]
When I tried to use the library in a web resource I got the "Xrm Context is not available" error every time. This was due to how the context is being grabbed from the dynamics-web-api.js file as it's looking for Xrm.Page directly instead of grabbing it from parent.Xrm.Page which is required in web resources. I fixed it with this minor change...
```javascript
if (typeof Xrm != "undefined") {
  return Xrm.Page.context;
} else if (typeof parent.Xrm != "undefined") {
  return parent.Xrm.Page.context;
} else {
  throw new Error("Xrm Context is not available.");
}
```
I can submit a PR if that helps but wanted to see if this was already handled some other way.

**Comment by AleksandrRogov** [comment]
Hi @geerzo ,
Where do you use your web resource, I believe it's not on the form. Is it on html page? Accessing parent window is not supported in CRM, that's why I did not add it to my library.

Please take a look at this [article](https://msdn.microsoft.com/en-us/library/gg328541.aspx#BKMK_GetGlobalContext), it describes how to get a Client-Side context outside of the form. So, if you add a reference to `ClientGlobalContext.js.aspx`, DynamicsWebApi will do the job for you.

Thank you
