### ISSUE TITLE
Issue with statecode

### ISSUE THREAD

**Issue by killi3000** [AleksandrRogov/DynamicsWebApi#18]
Is there an issue with updating `statecode` on activities? I am trying to set `statecode: 1`, but I cannot update the field. I am not getting an error, but the activity doesn't change in Dynamics.

**Comment by AleksandrRogov** [comment]
Hi @killi3000 ,
What activity type are you trying to update? (emails, tasks, etc...)

**Comment by killi3000** [comment]
it's a custom activity entity...

**Comment by AleksandrRogov** [comment]
Hi @killi3000 ,
Sorry for a delay with a reply. I tried to create my custom activity and update it using my library and it worked normally for both methods:

```js
var entity = {
    statecode: 1
};

dynamicsWebApi.update('845775AA-FCD6-E711-812C-480FCFF4B5B1', 'new_myactivity', entity).then(function (response) {
    // response was true and the entity has been updated
})
.catch(function (error) {
    console.log(error.message);
});
```

```js
var request = {
    collection: 'new_myactivity',
    key: '845775AA-FCD6-E711-812C-480FCFF4B5B1',
    entity: {
        statecode: 1
    }
};

dynamicsWebApi.updateRequest(request).then(function (response) {
    // response was true and the entity has been updated
})
.catch(function (error) {
    console.log(error.message);
});
```

**Comment by killi3000** [comment]
I see. I tried doing this on `dynamicsWebApi.create`, and that doesn't seem to work. I don't know Microsoft's API allows setting the `statecode` on create, but if they do it would be a nice feature to have. Otherwise I will just create a workaround.

**Comment by AleksandrRogov** [comment]
Hi @killi3000 ,
Yes, `statecode` is not valid for create operation and it does not depend on what endpoint you're using: Web Api or OrganizationService. Check [this table](https://msdn.microsoft.com/en-us/library/gg334225.aspx#attribute) (search by "statecode") it says that it is not valid for create.

I thought that you're trying to update the record. Also, note, that it's better also to set a `statuscode` together with `statecode` in one request, because, as you know, they depend on each other.
