### ISSUE TITLE
query functions as filters

### ISSUE THREAD

**Issue by wiese42** [AleksandrRogov/DynamicsWebApi#40]
Is it possible to use query functions such as LastXMonths (https://docs.microsoft.com/en-us/dynamics365/customer-engagement/web-api/lastxmonths) as filter statements? If I set the filter statement to 'Microsoft.Dynamics.CRM.LastXMonths(PropertyName=@p1,PropertyValue=@p2)&@p1='name'&p2=42'
I receive the server response 
"Syntax error: character '&' is not valid at position 70 in 'Microsoft.Dynamics.CRM.LastXMonths(PropertyName=@p1,PropertyValue=@p2)&@p1='name'&p2=42'."

**Comment by AleksandrRogov** [comment]
Hi @wiese42 ,
Should be possible. I am going to reproduce the issue and will get back to you.
Thanks

**Comment by AleksandrRogov** [comment]
Hi @wiese42 ,
It's not possible to set a filter with @p1, @p2 and so on properties at this moment. But you can use this query instead: `Microsoft.Dynamics.CRM.LastXMonths(PropertyName='name',PropertyValue=42)` where you explicitly set a property name and a value.

The reason why the original call is not working because I url-encode everything that is written in a 'filter' because I assume that it's a string that can contain a special symbol. So when you add `&@p1='name'` inside a 'filter' parameter DynamicsWebApi encodes it as `%26%40p1%3D'createdon'` which is not a valid parameter.

In one of the future release I may add a new property to advanced request called something like `queryProperties` where you can compose a request like this:
```js
var request = {
    collection: 'contacts',
    filter: 'Microsoft.Dynamics.CRM.LastXMonths(PropertyName=@p1,PropertyValue=@p2)'
    queryProperties: "@p1='name'&@p2=42"
}
```

I hope this solves your issue.

**Comment by wiese42** [comment]
Thanks Aleksandr. I can verify that the alternative query syntax works.
