### ISSUE TITLE
Dynamics change tracking functionality

### ISSUE THREAD

**Issue by andtrobs** [AleksandrRogov/DynamicsWebApi#57]
Is it possible to use the change tracking functionality of Dynamics as described [here](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/use-change-tracking-synchronize-data-external-systems)? I can't find anything documented to suggest if/how to do this.

**Comment by AleksandrRogov** [comment]
hi @andtrobs ,
Thank you for submitting this issue! There was a workaround how to get this done with v.1.5.10 but I have decided to simplify Change Tracking and included this feature in v.1.5.11. Please refer to README for more information. Here's an example how you can do change tracking:
```js
//set the request parameters
var request = {
    collection: "leads",
    select: ["fullname", "subject"],
    trackChanges: true
};

//perform a multiple records retrieve operation (1)
dynamicsWebApi.retrieveMultipleRequest(request).then(function (response) {

    var deltaLink = response.oDataDeltaLink;
    //make other requests to Web API
    //...

    //(2) only retrieve changes:
    return dynamicsWebApi.retrieveMultipleRequest(request, response.oDataDeltaLink);
})
.then(function (response) {
    //here you will get changes between the first retrieveMultipleRequest (1) and the second one (2)
})
.catch(function (error){
    //catch an error
});
```

Let me know if I missed something or you have any question.
Regards!

**Comment by andtrobs** [comment]
Hi @AleksandrRogov

Thanks for the update, this works great if the results fit into a single page of data, however if there are multiple pages the deltaLink is only included in the last page. It would be really useful if change tracking also worked with the retrieveAllRequest function.

Regards

**Comment by AleksandrRogov** [comment]
@andtrobs hi
Sorry for a delay with a reply, I did not have a test environment to test this. So, the delta link will be included when there are no more records to retrieve for the original request, which means, if you had a retrieve multiple request with multiple pages, the delta link will only be included in the last page. That's OOTB functionality of Dynamics 365 Web Api and it makes sense.

Do you have a sample that I can work with? Right now, I don't see why I would include it in `retrieveAllRequest`. My thoughts are below:

I do not want to include change tracking in `retrieveAllRequest`, because if during a request the record has been changed twice, it will be included twice in the final result. Also, if for some _magic_ reason there is a service that updates records quite frequently in Dynamics 365 the `retrieveAllRequest` might never stop running, because it will always have delta changes. That's highly unlikely, but still a food for thought. My suggestion is to implement a paging logic for your application manually.

Let me know if you have any suggestion.

Thanks

**Comment by AleksandrRogov** [comment]
@andtrobs what I can do though, is to include the delta link in the result of `retrieveAllRequest` that you can use further in change tracking. Will that be helpful?

**Comment by andtrobs** [comment]
Hi @AleksandrRogov including the delta link in the result of the retrieveAllRequest is what I was hoping for. My understanding is that the retrieveAllRequest will request each page and merge the results to return, if this also included the delta link it should work perfectly. Thanks

**Comment by AleksandrRogov** [comment]
@andtrobs I can include delta link in the result of the `retrieveAllRequest`.

For the merge, as I mentioned before, if during the request the entity changed twice, it will be included in the result twice. Also, there is a possibility that the request may never stop running and never return a result if there are non-stop changes in records.

**Comment by AleksandrRogov** [comment]
@andtrobs please check a new patch 1.5.12. I hope it'll help.

Thanks!
