### ISSUE TITLE
Batch error message to error objects

### ISSUE THREAD

**Issue by smoelle** [AleksandrRogov/DynamicsWebApi#62]
Hello,

I use the "ExecuteBatch" method to update multiple records. 
An error occurs, which is returned correctly. 

The response error message contains a lot of data that the user doesn't need to see.
Is there a way to return these messages as an "error"-array, so that I can show only the error message and the error code  to the user?

I had seen in the sources that there exists the "parseBatchResponse" method which would do the correct parseing.

Can it implemented in the library?

Best regards

**Comment by AleksandrRogov** [comment]
hi @smoelle . thank you for raising this issue!
I have made changes to the code, so now it returns parsed error object from a failed batch request. Please note, that the response you catch will be a type of array, because there can be multiple responses from separate requests, one of them will be an error (usually the last object in that array).

```js
dynamicsWebApi.startBatch();

dynamicsWebApi.retrieveMultiple('accounts');
dynamicsWebApi.update('00000000-0000-0000-0000-000000000002', 'contacts', { firstname: "Test", lastname: "Batch!" });
dynamicsWebApi.retrieveMultiple('contacts');

//execute a batch request:
dynamicsWebApi.executeBatch()
    .then(function (responses) {
       //parse response
    }).catch(function (response) {
        //response is an array
        //error will be at the same index as the failed request in the batch
    });
```

**Comment by smoelle** [comment]
Hi @AleksandrRogov,

thank you for the fast implementation and this great library.

Best regards
